version: '3.8'

services:
  csv-service:
    build: ./backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/usr/src/app
  web:
    build: ./calypso-ui
    ports:
      - "4200:4200"
    volumes:
      - ./calypso-ui:/usr/src/app
